[DEFAULT]
# TODO:: some configurations throw errors on initialization, add conditionals in initialization to ensure infeasible configurations parameters are not allowed
num_trials=2
iterations_per_trial=10
num_resources=3
num_agents=2
max_cover=2
resource_val_lb=2
resource_val_ub=5
agent_action_len_lb=2
agent_action_len_ub=2
agent_subset_len_lb=2
agent_subset_len_ub=2
beta=0.5
load_from_config=False
generate_graphics=False
algorithm=approximate_best_response