[DEFAULT]
# TODO:: some configurations throw errors on intialization, add conditionals in initialization to ensure infeasible configurations parameters are not allowed
num_trials=1
iterations_per_trial=1000
num_resources=4
num_agents=2
max_cover=2
resource_val_lb=5
resource_val_ub=15
agent_action_len_lb=3
agent_action_len_ub=5
agent_subset_len_lb=2
agent_subset_len_ub=3
beta=0.8
load_from_config=False
generate_graphics=True
algorithm=approximate_best_response