[DEFAULT]
# ---------- SYSTEM INITIALIZATION PARAMETERS ----------
num_trials=1
iterations_per_trial=1000
num_resources=30
num_agents=10
max_cover=2
resource_val_lb=5
resource_val_ub=60
agent_action_len_lb=2
agent_action_len_ub=3
agent_subset_len_lb=2
agent_subset_len_ub=5
load_from_config=False
generate_graphics=False
algorithm=genetic_response,approximate_best_response,logit_response,best_response
system_convergence_iter=100

# ---------- APPROXIMATE BEST RESPONSE PARAMETERS ----------
beta=0.5

# ---------- LOGIT RESPONSE PARAMETERS ----------
temperature=5.0

# ---------- GENETIC PARAMETERS ----------
population_size = 10000
# percent of how many agent current actions will be mutated
mutation_rate = 0.33
# tournament_k is the % of individuals from the population you will place in each tournament
tournament_k = 1000
num_parents = 2
# generational_size is the % of individuals to be in the next generation
generational_size = 0.95
k_crossover=3

# ---------- PARAMETER ANALYSIS SETTINGS ----------
# NOTE: True values trigger custom running configurations
analyze_beta=False
analyze_temperature=True