JSON_LOAD_PATH = "app/out/saved_models" # file path to preload system configurations
JSON_SAVE_PATH = "app/out" # save directory for all experiment data
BEST_RESPONSE="best_response"
APPROX_BEST_RESPONSE = "approximate_best_response"
LOGIT_RESPONSE = "logit_response"
BRUTE_FORCE = "brute_force"
MC_UTILITY = "marginal_contribution"
ES_UTILITY = "equal_share"
OPTIMISTIC_UTILITY = "optimistic"
DEFAULT_OPTIMISTIC_ALPHA = 0.1
BETA = "beta"
TEMP = "temp"
ERDOS_RENYI = "erdos_renyi"
RAND_GEO = "random_geometric"
WATTS_STROGATZ = "watts_strogatz"
MAX_BETA = 1.0 # maximum beta value when conducting beta analysis
BETA_STEP_SIZE = 0.025 # amount to change beta by each trial
MAX_TEMP = 15.0 # maximum temperature value when conducting temperature analysis
TEMP_STEP_SIZE = 0.5 # amount to change temperature by each trial #
HIST_BINS = 20 # amount of bins for histogram generation
EXCLUDE_KEYS = ["system", "data_collector", "data_key"]  # exclude some function params from data collection
VALID_DIST_NAMES = [BEST_RESPONSE, APPROX_BEST_RESPONSE, LOGIT_RESPONSE]
VALID_UTIL_NAMES = [MC_UTILITY, ES_UTILITY, OPTIMISTIC_UTILITY]
VALID_GRAPH_TYPES = [ERDOS_RENYI, RAND_GEO, WATTS_STROGATZ]
MAX_ERDOS_PROB = 0.70
MAX_GEO_RADIUS = 0.70
MAX_WS_BETA = 1.0
OPT_ITER_STEP_SIZE = 0.1
